"""The commodity watchlist: watchlist.csv (hand-edited) -> addon/WoWFAH/Watchlist.lua (generated)."""

from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path

import polars as pl

from wowfah.savedvars import quote

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CSV = ROOT / "watchlist.csv"
DEFAULT_LUA = ROOT / "addon" / "WoWFAH" / "Watchlist.lua"

COLUMNS = ["item_id", "name", "category", "bracket", "tags"]
_CATEGORY = re.compile(r"^[a-z0-9_-]+$")


@dataclass(frozen=True)
class Entry:
    item_id: int
    name: str
    category: str
    bracket: str
    tags: tuple[str, ...]


def load(path: str | Path = DEFAULT_CSV) -> list[Entry]:
    """Parse and validate watchlist.csv. Lines starting with # are comments."""
    path = Path(path)
    with path.open(newline="", encoding="utf-8") as f:
        lines = [line for line in f if line.strip() and not line.lstrip().startswith("#")]
    reader = csv.DictReader(lines)
    if reader.fieldnames != COLUMNS:
        raise ValueError(f"{path}: header must be {','.join(COLUMNS)}, got {reader.fieldnames}")

    entries: list[Entry] = []
    seen: set[int] = set()
    for row in reader:
        where = f"{path}: {row}"
        try:
            item_id = int(row["item_id"])
        except (TypeError, ValueError):
            raise ValueError(f"{where}: item_id must be an integer") from None
        if item_id in seen:
            raise ValueError(f"{where}: duplicate item_id {item_id}")
        seen.add(item_id)
        name = (row["name"] or "").strip()
        category = (row["category"] or "").strip()
        if not name:
            raise ValueError(f"{where}: name is required")
        if not _CATEGORY.match(category):
            raise ValueError(f"{where}: category must match {_CATEGORY.pattern}")
        tags = tuple(t.strip() for t in (row["tags"] or "").split(";") if t.strip())
        entries.append(Entry(item_id, name, category, (row["bracket"] or "").strip(), tags))
    return entries


def frame(entries: list[Entry]) -> pl.DataFrame:
    return pl.DataFrame(
        {
            "item_id": [e.item_id for e in entries],
            "name": [e.name for e in entries],
            "category": [e.category for e in entries],
            "bracket": [e.bracket for e in entries],
            "tags": [list(e.tags) for e in entries],
        },
        schema={"item_id": pl.Int64, "name": pl.String, "category": pl.String, "bracket": pl.String,
                "tags": pl.List(pl.String)},
    )


def check(entries: list[Entry], items: pl.DataFrame) -> tuple[list[str], list[str]]:
    """Compare the watchlist with item metadata. Returns (errors, warnings)."""
    joined = frame(entries).join(items.select("item_id", pl.col("name").alias("db_name"), "is_commodity"),
                                 on="item_id", how="left")
    errors, warnings = [], []
    for r in joined.iter_rows(named=True):
        label = f"{r['item_id']} {r['name']}"
        if r["db_name"] is None:
            errors.append(f"{label}: item id not found in item data")
        elif r["db_name"] != r["name"]:
            errors.append(f"{label}: item data calls it {r['db_name']!r}")
        elif not r["is_commodity"]:
            warnings.append(f"{label}: doesn't match the commodity rule (kept, since it's listed explicitly)")
    return errors, warnings


def to_lua(entries: list[Entry]) -> str:
    lines = [
        "-- Generated by `wowfah watchlist export` from watchlist.csv. Edit the CSV, not this file.",
        "local _, ns = ...",
        "",
        "-- { itemId, name, category }",
        "ns.WATCHLIST = {",
    ]
    lines += [f"    {{ {e.item_id}, {quote(e.name)}, {quote(e.category)} }}," for e in entries]
    lines += ["}", ""]
    return "\n".join(lines)


def export(csv_path: str | Path = DEFAULT_CSV, lua_path: str | Path = DEFAULT_LUA) -> list[Entry]:
    entries = load(csv_path)
    Path(lua_path).write_text(to_lua(entries), encoding="utf-8")
    return entries
